---
# 必須設定（テンプレートで実際に使用される変数のみ）
editor: nvim

# リポジトリ設定
neovim_config_repo: "https://github.com/kopug/neovim.git"

# Neovim設定（Linux用）
neovim_ppa: "ppa:neovim-ppa/unstable"

# 開発環境設定（gitignore.j2で使用）
development_environments:
  - node
  - python
  - go

# カスタムgitignoreパターン（gitignore.j2で使用）
custom_gitignore_patterns:
  - "# Project specific"
  - "*.local"
  - ".env.local"

# Git設定（gitconfig.j2で使用される部分のみ）
git_config:
  user:
    name: "Your Name"
    email: "your-email@example.com"
