---
# エディタ設定の統一
editor: nvim

# リポジトリ設定
neovim_config_repo: "https://github.com/kopug/neovim.git"

# Neovim設定（Linux用）
neovim_ppa: "ppa:neovim-ppa/unstable"

# パッケージ管理の統一
base_packages:
  common: ["curl", "wget", "unzip", "git", "vim", "zsh"]
  linux: []  # neovimは別途install_neovim_linux.ymlで処理
  macos: ["neovim"]

# 機能フラグの統一
features:
  github_cli: true
  docker: true
  docker_compose: true
  systemd: true

# 開発環境設定
development_environments:
  - node
  - python
  - go

# カスタムgitignoreパターン
custom_gitignore_patterns:
  - "# Project specific"
  - "*.local"
  - ".env.local"

# Git設定
git_config:
  user:
    name: "Your Name"
    email: "your-email@example.com"

# プラットフォーム検出のデフォルト値
is_wsl: false

# Volta設定
volta:
  version: "1.1.1"
  default_node_version: "lts"
  install_script_url: "https://get.volta.sh"
