---
- name: Setup Development Environment
  hosts: localhost
  connection: local
  gather_facts: yes
  pre_tasks:
    - name: Check if /proc/version exists (for WSL detection)
      stat:
        path: /proc/version
      register: proc_version_file
      when: ansible_system == "Linux"
      tags: always

    - name: Read /proc/version content for WSL detection
      slurp:
        src: /proc/version
      register: proc_version_content
      when: ansible_system == "Linux" and proc_version_file.stat.exists
      tags: always

    - name: Detect WSL environment
      set_fact:
        is_wsl: >-
          {{
            ansible_system == "Linux" and
            proc_version_file.stat.exists and
            ('microsoft' in (proc_version_content.content | b64decode | lower) or
             'wsl' in (proc_version_content.content | b64decode | lower))
          }}
      when: ansible_system == "Linux"
      tags: always

    - name: Set is_wsl to false for non-Linux systems
      set_fact:
        is_wsl: false
      when: ansible_system != "Linux"
      tags: always

    - name: Display detected environment
      debug:
        msg: "Detected environment: {{ ansible_system }}{{ ' (WSL)' if is_wsl else '' }}"
      tags: always

    - name: Set platform group
      group_by:
        key: "{{ 'wsl' if is_wsl else ansible_system | lower }}"
      tags: always

  roles:
    - role: common
      tags: common
    - role: wsl
      when: ansible_system == "Linux" and is_wsl
      tags: wsl
    - role: macos
      when: ansible_system == "Darwin"
      tags: macos
    - role: docker
      when: ansible_system == "Linux" and is_wsl and docker_enabled | default(false)
      tags: docker

  post_tasks:
    - name: Display completion message
      debug:
        msg:
          - "=== Setup Complete! ==="
          - "Platform: {{ ansible_system }}{{ ' (WSL)' if is_wsl else '' }}"
          - "Next steps:"
          - "1. Restart your shell session"
          - "2. Test SSH: ssh-add -l"
          - "3. Test GitHub: ssh -T git@github.com"
          - "4. Start Neovim: nvim"
          - "{{ '5. Test Docker: docker run hello-world' if (ansible_system == 'Linux' and is_wsl and docker_enabled | default(false)) else '' }}"
      tags: always
