---
- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install common packages
  apt:
    name: "{{ base_packages.common }}"
    state: present
  become: yes

- name: Install Linux-specific packages
  apt:
    name: "{{ base_packages.linux }}"
    state: present
  become: yes
  when: base_packages.linux | length > 0

- name: Install WSL-specific packages
  apt:
    name: "{{ wsl_specific_packages | default([]) }}"
    state: present
  become: yes
  when: ansible_system == "Linux" and is_wsl
