---
- name: Install base packages
  include_tasks: "install_packages_{{ ansible_system | lower }}.yml"
  tags: packages

- name: Setup SSH configuration
  include_tasks: setup_ssh.yml
  tags: ssh

- name: Setup Git configuration
  include_tasks: setup_git.yml
  tags: git

- name: Setup Neovim
  include_tasks: setup_neovim.yml
  tags: neovim

- name: Setup Volta (Node.js version manager)
  include_tasks: setup_volta.yml
  tags: volta

- name: Setup shell environment
  include_tasks: setup_shell.yml
  when: ansible_system == "Linux"
  tags: shell
